### ISSUE TITLE
Textmining Mapping

### ISSUE THREAD

**Issue by Monika-Mistry** [Rothamsted/knetbuilder#1]
Create textmining relations with homolog proteins instead of actual species.
e.g. Human Disease -> cooccur_with relation to Mouse homolog and not Human protein.

**Comment by marco-brandizi** [comment]
@AjitPS, @KeywanHP, is this resolved or outdated? Could someone close it?

**Comment by KeywanHP** [comment]
The text mining methods need to be reviewed in due time. Closing this for now.
