### ISSUE TITLE
OrthoXML parser has problems with hierarchical-groups output

### ISSUE THREAD

**Issue by KeywanHP** [Rothamsted/knetbuilder#2]
The OrthoXML parser seems to have a problem with nested ortholog groups.

Use the ortho-xml java library (API) to parse it

http://www.orthoxml.org/xml/OrthoXML_Java.html

**Comment by Monika-Mistry** [comment]
Here is some example data with nested ortholog groups

[HierarchicalGroups.part.zip](https://github.com/Rothamsted/ondex-knet-builder/files/865240/HierarchicalGroups.part.zip)

**Comment by marco-brandizi** [comment]
@KeywanHP is this resolved or outdated? Please, could you close it if yes?

**Comment by marco-brandizi** [comment]
Closing, reopen if it still needs changes.
