### ISSUE TITLE
UniProtKB parser issues with diseases

### ISSUE THREAD

**Issue by KeywanHP** [Rothamsted/knetbuilder#20]
Example protein: https://www.uniprot.org/uniprot/P21810

Parse all this information:

```xml
<comment type="disease" evidence="7">
<disease id="DI-04786">
<name>Spondyloepimetaphyseal dysplasia, X-linked</name>
<acronym>SEMDX</acronym>
<description>
A X-linked recessive bone disease characterized by severe short-trunk dwarfism, brachydactyly, metaphyseal flaring of lower extremities, short and broad long bone diaphyses, moderate platyspondyly, normal facies, and normal intelligence.
</description>
<dbReference type="MIM" id="300106"/>
</disease>
<text>
The disease is caused by mutations affecting the gene represented in this entry.
</text>
</comment>
```
Do not parse this:

```xml
<dbReference type="MIM" id="300106">
<property type="type" value="phenotype"/>
</dbReference>
<dbReference type="MIM" id="300989">
<property type="type" value="phenotype"/>
</dbReference>
<dbReference type="MIM" id="301870">
<property type="type" value="gene"/>
</dbReference>
```

**Comment by josephhearnshaw** [comment]
Issue is as follows:

UniProt Parser will parse any fields containing <disease> tag; including those without descriptions for diseases, leading to Disease traits appearing with just accession ID's and not much else. 

I will resolve this by ensuring it only parses where description fields are present.

**Comment by marco-brandizi** [comment]
It might be worth to import these OMIM cross-references as protein-linked empty concepts, then import OMIM data, to get ref details, then merge OMIM concepts by accession, then I remember there is some filter able to remove non-linked concepts.

But I don't know if the above references are imported as separated concepts or in another form (eg, protein attributes). In the latter case, we would require changes to the parser code.

**Comment by colinliCitrolius** [comment]
That's our existing approach, the UniProt parser creates Protein-Disease relations with MIM accessions added to Disease concepts. But there is the issue that the UniProt parses converts this:

```xml
<dbReference type="MIM" id="301870">
<property type="type" value="gene"/>
</dbReference>
```
into a Disease concepts although it's a "Gene". It seems to be ignoring the `value="gene"` attribute.

Besides we thought it would be nice to parse the disease name/description directly from UniProt instead of relying on messy OMIM data.

**Comment by KeywanHP** [comment]
That's our existing approach, the UniProt parser creates Protein-Disease relations with MIM accessions added to Disease concepts. But there is the issue that the UniProt parses converts this:

```xml
<dbReference type="MIM" id="301870">
<property type="type" value="gene"/>
</dbReference>
```
into a Disease concepts although it's a "Gene". It seems to be ignoring the `value="gene"` attribute.

Besides we thought it would be nice to parse the disease name/description directly from UniProt instead of relying on messy OMIM data.

**Comment by KeywanHP** [comment]
I think @josephhearnshaw resolved this.
