### ISSUE TITLE
Only parse UniProt data containing a specific keyword within Publications

### ISSUE THREAD

**Issue by josephhearnshaw** [Rothamsted/knetbuilder#22]
It would be good to enable a way to filter the OXL data directly based upon a search term being present within a Publication; this would create more concise and relevant knowledge-networks. 

i.e. Searching for Alzheimer's to create a more Alzheimer's specific OXL for Human. Or a search term for more specific plant datasets. This may be useful for certain diseases in both Animals & Plants, respectively. 

Can be expanded to include 'AND', 'OR', 'AND+' statements.

**Comment by marco-brandizi** [comment]
Filtering a particular import based on another particular import is too specific to be good. This might be a better approach: a filter plug-in having methods like `boolean filterConcept( concept )` and `boolean filterRelation( relation )`, which would allow for deciding what concepts to retain one-by-one, based on criteria like being related to a publication with certain keywords.

Possibly, this could have a subclass that accepts groovy files as implementations of the two filtering methods.

**Comment by KeywanHP** [comment]
Agree this is too specific. There are other ways of achieving this.
