### ISSUE TITLE
Migration to new Nexus, outdated or no-longer available dependencies

### ISSUE THREAD

**Issue by marco-brandizi** [Rothamsted/knetbuilder#23]
While migrating Ondex to our [new Nexus](https://knetminer.org/artifactory), I've discovered a number of Ondex 3rd-party dependencies that:

  * either are very old and cannot be found in any public Maven repository anymore
  * or have never been proper Maven projects, but someone made a Jar in more manual ways (eg, via IDE) and uploaded it in the old Nexus.

In the first case, I tried to find more recent versions or replacements. Some of them worked, but **we need entensive testing of the new build**. In particular, we need to re-run relevant Mini workflows (ara, wheat, etc) and see if the resulting OXL is fine.

In the second case (and in cases where no version or replacement was available), **I had to disable modules that depends on those missing components**. These are:

<table class="table table-bordered table-hover table-condensed">
<thead><tr><th title="Field #1">Ondex Module ID</th>
<th title="Field #2">Module Name</th>
<th title="Field #3">URL</th>
<th title="Field #4">Lost Deps</th>
</tr></thead>
<tbody><tr>
<td>nclondexexpression</td>
<td>NCL Ondex Expression</td>
<td>https://github.com/Rothamsted/ondex-opt/tree/master/modules-opt/expression</td>
<td>de.mpg.mpiinf.csb:KPM</td>
</tr>
<tr>
<td>psimi2ondex</td>
<td>PSI-MI 2.5 parser for Ondex</td>
<td>https://github.com/Rothamsted/ondex-opt/tree/master/modules-opt/psimi25</td>
<td>uk.ac.ncl.cs:psimi</td>
</tr>
<tr>
<td>sbml</td>
<td>sbml</td>
<td>https://github.com/Rothamsted/ondex-opt/tree/master/modules-opt/sbml</td>
<td>org.biojava:biojava:1.0</td>
</tr>
</tbody></table>

**We need to confirm that the above modules aren't needed anymore**. Or to discuss a solution.

**Comment by KeywanHP** [comment]
I can confirm they are not needed any longer. It might be a good idea to spring clean our plugins and just keep the ones that are used for building KnetMiner knowledge graphs.
