### ISSUE TITLE
Knetbuilder is working not working for 3.0 while it is working for 1.2 

### ISSUE THREAD

**Issue by man4ish** [Rothamsted/knetbuilder#33]
I am using following command to build in ondex-mini folder.

./runme.sh ../tutorial_files/Workflow/HumanDiseaseKNET.xml. It is not working for 3.0 while it is working for 1.2. May i know know what is the issue?

**Comment by marco-brandizi** [comment]
Could you provide us with details? What do you have in the XML? What output do you get from the command? Could you send us the latter (using output redirection) and also the ondex.log file?

**Comment by man4ish** [comment]
I updated java in my system.

openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10-post-Ubuntu-2ubuntu116.04)
OpenJDK 64-Bit Server VM (build 11.0.5+10-post-Ubuntu-2ubuntu116.04, mixed mode, sharing)

And ran the same command as above but still getting issue.

[java11-ondex.log](https://github.com/Rothamsted/knetbuilder/files/5409600/java11-ondex.log)
[java11-output.txt](https://github.com/Rothamsted/knetbuilder/files/5409602/java11-output.txt)

**Comment by marco-brandizi** [comment]
Version 3.0 doesn't work with Java > 8. `JAXBContext` not found means it isn't included with its dependencies cause it used to be available from the JDK, while it was removed in recent Java versions.

If you want to use Knetbuilder with J11, you should download the latest snapshoot, see [here](https://github.com/Rothamsted/knetbuilder/wiki/Downloads).

The original error about the mapping plugin yielding a null pointer exception from Lucene, it's due to #29: certain accession formats (eg, '-') aren't accepted by Ondex. You should review your input files, almost certainly you have wrong accessions.

**Comment by man4ish** [comment]
I am just trying to recreate the tutorial example described here https://github.com/Rothamsted/knetbuilder/blob/master/README.md    So none of it is my data. The tutorial files are here https://rrescloud.rothamsted.ac.uk/index.php/s/H6sl0RIT9CoMaUI/download
How do I fix this?

**Comment by KeywanHP** [comment]
Sorry, we will need to update the README as some of the tutorial datasets are not compatible with version 3.0.

The latest knetbuilder tutorial 3.0 with tested datasets and workflows can be found in our wiki:
https://github.com/Rothamsted/knetbuilder/wiki/Building-Knowledge-Networks

Hope this helps.

**Comment by man4ish** [comment]
Thanks i will play with and report back. Is there any build script for Arabidopsis KG v45 (https://knetminer.com/tutorial/knetbuilder/arabidopsis_45.oxl) file?

**Comment by KeywanHP** [comment]
Yes there is but it's not open-access. The arabidopis_45.oxl contains datasets that are a few years old. Newer Arabidopsis KGs and build scripts can be licensed from us. Drop me a DM or an email if you would like to discuss the licensing terms and pricing plans.

**Comment by man4ish** [comment]
Thanks for prompt reply. I was just curious to know about the scripts for generating arabidopis_45.oxl and currently focussing on other methods for our analysis.
