### ISSUE TITLE
how can I acquire the specific dataset (e.g rice) of KnetMiner ？

### ISSUE THREAD

**Issue by Cyviva** [Rothamsted/knetbuilder#54]
hello ,could you please tell me how to get access to the whole dataset of rice ,I just wanna run KnetMiner locally using the specific dataset of rice,but I cannot find related files about rice dataset. 
Looking forward to your reply ，thank you.

**Comment by KeywanHP** [comment]
@Cyviva are you still interested in the rice dataset? Please contact us at support@knetminer.com.

**Comment by Cyviva** [comment]
@KeywanHP thanks a lot, I would appreciate it if I could acquire some test datasets about rice.
