### ISSUE TITLE
CytoscapeJS plugin, add option to export pure-JSON

### ISSUE THREAD

**Issue by marco-brandizi** [Rothamsted/knetbuilder#66]
`net.sourceforge.ondex.export.cyjsJson.Export` exports JSON-like data in this format:

```javascript
{
  "graph": "var graphJSON= { \"nodes\": [{ \"data\": { \"annotation\": \"PROTEIN_CODING\" ...
  var allGraphData= { \"ondexmetadata\": { \"graphName\": \"FilteredGraphUnconnected\", \"concepts\": [{...}]...};"
}
```

A [real example](https://knetminer.com/araknet/network?&list=AT2G39940). The class comments has more details on it.
While this is a structure that is useful for the Javascript that builds the network view, it's not useful anywhere else.

We need to add a boolean argument to the `Exporter` plug-in, named like `exportPlainJSON` (default is false). If this is set, we need to call a variant of `writeJSONToFile()`, let's say `writePlainJSON()`, which will produce actual JSON, in a form like:

```javascript
{
  "graphJSON": { 
     "nodes": [...],
     "edges": [...]
   },
  "allGraphData": {
     "ondexmetadata": {...}
  }
```

That is, "graph" is removed from the root, no variable declaration, no comma escaping, just plain JSON should come out of it. This is easy to produce, we just need to compose graphJson and metadataJson into a new `JSONObject` and then write the latter using its `toString()`, no `formatJson()`, no semicolon or '=' addition.

This new plug-in argument will come from the Knetminer API (about to write a separated ticket for it).

**Comment by jojicunnunni** [comment]
[cy-export-basics-test.txt](https://github.com/Rothamsted/knetbuilder/files/9055498/cy-export-basics-test.txt)

**Comment by marco-brandizi** [comment]
Thanks, @jojicunnunni, I'm closing this.

**Comment by Arnedeklerk** [comment]
Example outputs:

Frontend clean json for cytoscape desktop: [knetminer_network.zip](https://github.com/Rothamsted/knetbuilder/files/10391548/knetminer_network.zip) exported from https://knetminer.com/ci-test/client/ using keyword: drought and TRAESCS5A02G149800 as a gene list.

The same output, in the old cytoscape format looks like: https://knetminer.com/ci-test/ws/wheatknet-beta/network?exportPlainJSON=true&list=TRAESCS5A02G149800&keyword=drought

More examples can be generated yourself, but here are two more, which are also smaller:

1. flowering + TRAESCS3D02G468400 = [FloweringExample.zip](https://github.com/Rothamsted/knetbuilder/files/10391599/FloweringExample.zip) and https://knetminer.com/ci-test/ws/wheatknet-beta/network?exportPlainJSON=true&list=TRAESCS3D02G468400&keyword=flowering

2. dormancy + TRAESCS3B02G257900 =  [DormancyExample.zip](https://github.com/Rothamsted/knetbuilder/files/10391636/DormancyExample.zip) and https://knetminer.com/ci-test/ws/wheatknet-beta/network?exportPlainJSON=true&list=TRAESCS3B02G257900&keyword=dormancy
