### ISSUE TITLE
Text-mining occ_in/cooc_wi relations

### ISSUE THREAD

**Issue by Monika-Mistry** [Rothamsted/knetbuilder#9]
In the Rice network, the gene **OS04G0350700** (An-1) has a network of around 15200 concepts and is too big to look into on KnetMiner. ([OS04G0350700.zip](https://github.com/Rothamsted/ondex-knet-builder/files/1145252/OS04G0350700.zip))

It’s connected to 62 TO terms via text-mining including submergence sensitivity. Text-mining found occ_in relations to 14700 publications. Some of the publications are linked as **An-1** occurs in chemical names (e.g. but**an-1**-ol) or they are linked as **an1** in the publication within words (e.g. BRRI hybrid dh**an1**, var. CP**AN1**676).

cooc_wi relations TO term 'endosperm quality' has a synonym 'end' (e.g. 5'**end** in publications)

**Comment by Monika-Mistry** [comment]
I'll look into i

**Comment by marco-brandizi** [comment]
@AjitPS, please, close this if it's resolved/outdated.
